### ISSUE TITLE
Criação do rodapé com redes sociais

### ISSUE THREAD

**Issue by Azanniel** [PyNorte/pynorte2023-site#10]
## Descrição ✨

Com a ideia de extrair pequenas partes do site para que todos possam colaborar, uma das partes que pode ser densevolvida independente das demais é o rodapé do site contento as redes sociais.

![Image](https://user-images.githubusercontent.com/71537090/233799747-4236fb88-a53b-48a9-ad70-49168adcd41e.png)

No protótipo acima temos a visualização em mobile, mas é importante tentar entender como seria essa visualização em formato web para poder implementar.

> ⚠️ Quanto aos links ainda não temos previsão do que serão, logo é opcional a adição deles, pois ainda não têm sentindo implementar os mesmos.

## Objetivos 🎯

- [ ] Implementação do rodapé do site contendo logo, descrição e redes sociais

**Comment by ramontrovao** [comment]
Vou realizar essa task. 😉

**Comment by Azanniel** [comment]
Seria bom falar com o time de design na comunidade do discord para ter uma ideia de como é o layout web @ramontrovao
