### ISSUE TITLE
Criação da página de código de conduta

### ISSUE THREAD

**Issue by Azanniel** [PyNorte/pynorte2023-site#11]
## Descrição ✨

O evento PyNorte 2023 deve exibir em seu site o código de conduta que já está descrito por @thaty-maru. Para isso é necessário uma página de código de conduta como mostra o protótipo.

![Image](https://user-images.githubusercontent.com/71537090/233802432-8dbfbc59-1776-4064-9b9f-8e242947ae6c.png)

Na implementação dessa página deve-se observar também seu layout web com o time de design.

## Objetivo 🎯

- [ ] Criação da página de código de conduta de acordo com o protótipo [web - mobile]

**Comment by surocham** [comment]
Posso ficar com essa ?

**Comment by Azanniel** [comment]
> Posso ficar com essa ?

Á vontade @suamirocha

**Comment by surocham** [comment]
do mobile e desktop tbm ou só de um ?

**Comment by Azanniel** [comment]
> do mobile e desktop tbm ou só de um ?

São os dois, tanto mobile quanto desktop

**Comment by thaty-maru** [comment]
@junowoz já tem a issue aqui. O texto é esse:

Código de conduta

O evento Python Norte é um ambiente amistoso, de boa convivência, inclusivo e livre de intimidação, onde todas as pessoas são bem-vindas e a civilidade é exigida.
Com esta finalidade, a organização do evento conta com uma Equipe de Resposta que atua para garantir um ambiente com essas qualidades.
Por isso:
Não é tolerado nenhum tipo de assédio, discriminação inapropriada ou humilhação pública;
Não é tolerado o descumprimento das leis brasileiras;
Toda pessoa presente no evento, independente do seu papel, está sujeita a estas regras.
Desta forma, entendemos que:
Assédio é a ação de insistir, perseguir ou coagir outra pessoa a um comportamento involuntário.;
Discriminação inapropriada é o ato de separar, injuriar ou humilhar alguém promovendo sua exclusão por atributo particular da mesma.
Humilhação pública é o ato de submeter, rebaixar, ridicularizar ou promover o vexame de outro publicamente.
O público alvo do evento também inclui crianças e adolescentes, por isso buscamos manter um ambiente apropriado para todas as faixas etárias. Sendo assim, linguagem e imagens sexualizadas não são adequados para palestras e ações promocionais de patrocinadores.
Se você se sentiu assediado, discriminado indevidamente ou humilhado, ou presenciou alguma destas atitudes, por favor entre em contato com a Equipe de Resposta.
Havendo um relato de violação destes princípios, a Equipe de Resposta realizará a devida análise e, quando necessário, tomará as ações para impedir a reincidência. Estas ações podem, mas não se restringem nem implicam em ir desde uma conversa em busca da retratação até um convite a se retirar do evento por tempo indeterminado.




Códigos e conduta APYB para Python Norte

Código de Conduta do Evento Python Norte
O evento Python Norte é um ambiente amistoso, de boa convivência, inclusivo e livre de intimidação, onde todas as pessoas são bem-vindas e a civilidade é exigida.

Com esta finalidade, a organização do evento conta com uma Equipe de Resposta que atua para garantir um ambiente com essas qualidades.

Por isso:

Não é tolerado nenhum tipo de assédio, discriminação inapropriada ou humilhação pública;
Não é tolerado o descumprimento das leis brasileiras;
Toda pessoa presente no evento, independente do seu papel, está sujeita a estas regras;
Desta forma, entendemos que:

Assédio é a ação de insistir, perseguir ou coagir outra pessoa a um comportamento involuntário.
Discriminação inapropriada é o ato de separar, injuriar ou humilhar alguém promovendo sua exclusão por atributo particular da mesma.
Humilhação pública é o ato de submeter, rebaixar, ridicularizar ou promover o vexame de outro publicamente.
O público alvo do evento também inclui crianças e adolescentes, por isso buscamos manter um ambiente apropriado para todas as faixas etárias. Sendo assim, linguagem e imagens sexualizadas não são adequados para palestras e ações promocionais de patrocinadores.

Se você se sentiu assediado, discriminado indevidamente ou humilhado, ou presenciou alguma destas atitudes, por favor entre em contato com a Equipe de Resposta.

Havendo um relato de violação destes princípios, a Equipe de Resposta realizará a devida análise e, quando necessário, tomará as ações para impedir a reincidência. Estas ações podem, mas não se restringem nem implicam em ir desde uma conversa em busca da retratação até um convite a se retirar do evento por tempo indeterminado.
