### ISSUE TITLE
Criação de rotas para a aplicação e página de conteúdo não encontrado

### ISSUE THREAD

**Issue by Azanniel** [PyNorte/pynorte2023-site#12]
## Contexto 🔮

No website do evento PyNorte 2023 teremos algumas páginas além da landing, como:

- [Página de código de conduta](https://github.com/PyNorte/pynorte2023-site/issues/11)
- Página para organizadores

E entre outras que ainda vão ser descritas pela comunidade.

O ponto é que essas páginas precisam ser geridas por um esquema de rotas.
Para a implementação das rotas foi decidido que iríamos utilizar o [React Router Dom](https://reactrouter.com/en/main) que dá suporte a diversas funcionalidades incríveis que podemos implementar no projeto.

E para as primeiras rotas da aplicação foi pensado na:

- Rota inicial
- Rota de página não encontrada

Essas duas são rotas essenciais para o primeiro ponto do projeto.

## Objetivos 🎯

- [ ] Implementação do React Router DOM
- [ ] Criação da página de 404

**Comment by ramontrovao** [comment]
Vou realizar essa task. 😉
