### ISSUE TITLE
Criação da sessão de sobre a PyNorte

### ISSUE THREAD

**Issue by ramontrovao** [PyNorte/pynorte2023-site#18]
# Objetivo 🎯

- [ ] Desenvolvimento da sessão "Sobre a PyNorte" do site
 
Deixarei alguns screenshots abaixo para melhor entendimento sobre o que precisa ser feito baseado no [figma](https://www.figma.com/file/PPJFp5QmqQZ3l1ic7tBauK/Wireframes?node-id=0%3A1&t=KPryq80wwnaUrzCa-1)

# Screenshots 📸

| Desktop | Mobile |
| --------- | -------- |
| ![image](https://user-images.githubusercontent.com/73340502/235358791-937ebf70-7780-4367-a06e-6174b942244f.png) | ![image](https://user-images.githubusercontent.com/73340502/235358805-41a9fa8f-fc61-4bec-897a-4c842bf041c5.png)

# Observações 👀

Favor consultar o time de Comunicação para definir o conteúdo do texto dessa sessão.

**Comment by Azanniel** [comment]
Adicionei as imagens em formato de tabela para melhoria de visualização. Espero que ajude.

**Comment by davimoreiraa** [comment]
Tem alguém já fazendo essa task? Posso fazer

**Comment by Azanniel** [comment]
Acredito que ela ja tenha sido feita @davimoreiraa 

https://2023.pythonnorte.org/#/preview
