### ISSUE TITLE
Adição de uma licença para o projeto

### ISSUE THREAD

**Issue by Azanniel** [PyNorte/pynorte2023-site#3]
## Descrição 📄

O projeto foi criado sem uma licença e agora precisamos decidir em comunidade qual a melhor licença para se adotar no projeto.

## Objetivo ✨

- [x] Estabelecer uma linceça a qual o projeto será regido
- [x] Adicionar menção a licença no readme

## Observações pessoais 🥸

Uma das coisas que vejo é que esse projeto parece ser aberto a todos que queiram colaborar, precisamos saber se pode ser usado por terceiros e entre outras coisas. 
Com isso seria interessante procurar uma licença que esteja de acordo com as diretrizes que os organizadores (@thaty-maru e @gabrovskii) desejam.

**Comment by Azanniel** [comment]
@thaty-maru  você poderia me indicar alguém que tenha conhecimento sobre licenças? É fundamental que possamos escolher uma licença apropriada para o projeto em questão.

**Comment by thaty-maru** [comment]
> @thaty-maru você poderia me indicar alguém que tenha conhecimento sobre licenças? É fundamental que possamos escolher uma licença apropriada para o projeto em questão.

Eu acredito que o @rougeth tenha mais propriedade sobre isso

**Comment by rougeth** [comment]
O que o @Azanniel escreveu é importante, a escolha da licença precisa levar em consideração as diretrizes que a organização do evento desejam. Vocês querem limitar o uso do código em algum aspecto? Na minha opinião, o uso de uma licença permissiva é o mais apropriado, como MIT ou Apache 2.0.

**Comment by Azanniel** [comment]
@thaty-maru ou @gabrovskii saberiam nos dizer quais seriam essas diretrizes para levarmos em consideração no momento da escolha da melhor licença permissiva?
