### ISSUE TITLE
Inserção do FAQ

### ISSUE THREAD

**Issue by thaty-maru** [PyNorte/pynorte2023-site#31]
## Texto do FAQ:

# O que é a Python Norte 2023?
Python Norte 2023 é o maior evento sobre a linguagem de programação Python da região Norte. É suportado por diversos eventos locais e regionais, culminando em um encontro amigável e itinerante dentro da região Norte.

# O evento será presencial ou on-line?
> A Python Norte 2023 será realizado na modalidade presencial, sem a possibilidade de transmissão ao vivo da programação.

# Preciso estar vacinado contra febre amarela?
> Segundo a Secretaria Municipal de Saúde (Semsa Manaus), a Região Amazônica é endêmica para Febre Amarela, por isso, o turista deverá ser vacinado contra esta doença com pelo menos 10 dias de antecedência da viagem. Mais informações aqui [GUIA DE SAÚDE PARA O TURISTA - SEMSA](https://semsa.manaus.am.gov.br/servico_cidadao/guia-de-saude-para-o-turista/#:~:text=A%20Regi%C3%A3o%20Amaz%C3%B4nica%20%C3%A9%20end%C3%AAmica,dias%20de%20anteced%C3%AAncia%20da%20viagem)

# Preciso estar vacinado para participar do evento?
> De acordo com a OMS, a pandemia foi declarada finalizada no dia 05 de Maio de 2023. No entanto, reforçamos a importância de manter o cartão de vacinação atualizado pelo fato do evento ser presencial.

# Onde e quando será realizado o Python Norte 2023?
> O evento irá ocorrer presencialmente na cidade de Manaus, no Amazonas, nos dias 29 e 30 de Setembro de 2023, na UNINORTE UNIDADE DJALMA BATISTA.

# Qual a programação do evento?
> A programação do evento estará disponível nas redes sociais assim que possível. Acompanhe-nos.

# O evento é apenas em português?
> A priori sim, pois não houve nenhum tipo de demanda de outras linguagens até o momento.

# O que é Job Fair?
> Job Fair é uma feira de empregos, onde as empresas mostram como e onde elas atuam, além de conversar sobre vagas e o que esperam de quem submete.

# Como participar do Job Fair?
> Basta conferir o horário da empresa que você deseja participar e participar da apresentação na sala específica de Job Fair.

**Comment by junowoz** [comment]
DONE 🆗
