### ISSUE TITLE
Inserção do patrocinador Vinta

### ISSUE THREAD

**Issue by thaty-maru** [PyNorte/pynorte2023-site#32]
![image](https://github.com/PyNorte/pynorte2023-site/assets/97703494/31e8ecfd-09f5-4763-826b-af1622def239)

- Retirar as colunas vazias até o momento (ou deixar invisível para os futuros patrocinadores)
- Inserir a logo da Vinta enviado no Discord na coluna de patrocinador Bronze

**Comment by junowoz** [comment]
DONE 🆗
