### ISSUE TITLE
Mudar os dados de redes sociais e contato

### ISSUE THREAD

**Issue by thaty-maru** [PyNorte/pynorte2023-site#36]
![Image](https://github.com/PyNorte/pynorte2023-site/assets/97703494/376539a3-2add-4bdb-95e6-433253e698e7)

- [ ] Alterar os links de redes sociais para os que estão na tela atual
- [ ] Inserir o e-mail de contato pynorteam@gmail.com

**Comment by junowoz** [comment]
DONE 🆗
