### ISSUE TITLE
Criação de cabeçalho, área principal e sobre a PyNorte

### ISSUE THREAD

**Issue by Azanniel** [PyNorte/pynorte2023-site#4]
## Descrição 📑

Como desenvolvimento incial seria interessante desenvolver a parte principal do site que contém o botão de inscrição e um descritivo sobre a PyNorte.

## Objetivo 🎯

- [ ] Desenvolvimento do cabeçalho do site
- [ ] Desenvolvimento da área principal
- [ ] Desenvolvimento da área de conteúdo sobre a python norte 2023

Abaixo estamos deixando alguns screenshots para melhor entendimento sobre o que precisa ser feito baseado no [figma](https://www.figma.com/file/PPJFp5QmqQZ3l1ic7tBauK/Wireframes?node-id=0%3A1&t=KPryq80wwnaUrzCa-1)

### Screenshots

**1. Cabeçalho e área principal**

Infelizmente só temos o layout mobile, mas o layout web está a caminho de acordo com @thaty-maru e @gabrovskii.

🟪 - A parte do cabeçalho deve conter a logo e deve ver a necessidade do uso do menu, pois ainda não se sabe as outras páginas do site. No entanto, pode-se consultar o time de design na comunidade para entender como esse componente irá se comportar ou até mesmo se será mostrado no figma.

🟦 - Na área principal temos o conteúdo com a data do evento e um botão de inscrição que, enquanto não temos o link da inscrição no sympla, deve ser colocado algo como `Logo abriremos as inscrições`.

![Image](https://user-images.githubusercontent.com/71537090/233206084-51530e64-0fb0-4e30-ab82-dcc661f95e52.png)

**2. Conteúdo sobre a PyNorte**

Nessa parte você deve estar atento a mudança de background que ocorre ao realizar o scroll da página.

![Image](https://user-images.githubusercontent.com/71537090/233207126-794d13ec-050a-4c02-9c29-960d2d9f7438.png)

**Comment by ramontrovao** [comment]
Vou realizar essa task.

**Comment by ramontrovao** [comment]
Você não acha melhor dividir essa issue em 3? Cabeçalho, section inicial e section de sobre a PyNorte?

**Comment by Azanniel** [comment]
É uma boa ideia, consegue criar essa issue na aba de issues do repo?

**Comment by ramontrovao** [comment]
> É uma boa ideia, consegue criar essa issue na aba de issues do repo?

Consigo sim, vou criar agora.
