### ISSUE TITLE
Configuração do deploy para site

### ISSUE THREAD

**Issue by gabrovskii** [PyNorte/pynorte2023-site#6]
Olá @luzfcb, estamos tentando linkar o repositório [pynorte2023-site](https://github.com/PyNorte/pynorte2023-site) com  com a Plataforma [Vercel](https://vercel.com) e aparentemente eu não tenho permissão para fazer, você poderia ajudar a gente com isso?

A vercel foi a plataforma escolhida para fazer o deploy do site da Python Norte 2023.

**Comment by luzfcb** [comment]
@gabrovskii acho que de graça não vai rolar o vercel não.
Qual horario você tem disponível para fazer-mos uma reunião rapida amanhã e resolver isso?

![image](https://user-images.githubusercontent.com/807599/233235552-6d59b8ac-cbc6-4914-8bcb-f5d3acf0bc13.png)

**Comment by Azanniel** [comment]
Já existe alguma opção de plataforma para deploy que já usam?

**Comment by Azanniel** [comment]
> @gabrovskii acho que de graça não vai rolar o vercel não. Qual horario você tem disponível para fazer-mos uma reunião rapida amanhã e resolver isso?
> 
> ![image](https://user-images.githubusercontent.com/807599/233235552-6d59b8ac-cbc6-4914-8bcb-f5d3acf0bc13.png)

Acredito que não precise configurar a plataforma da vercel para times, até porque a organização é a própria proprietária do repo.

**Comment by gabrovskii** [comment]
@Azanniel quando podemos marcar uma reunião com o fábio para resolver isso? acredito que não precisamos mais de 20 minutos.

**Comment by Azanniel** [comment]
@gabrovskii acredito que por volta das 19:00 (brasília)

**Comment by luzfcb** [comment]
@Azanniel 

> Acredito que não precise configurar a plataforma da vercel para times, até porque a organização é a própria proprietária do repo.

A mensagem para mim é bem clara. Desde que o código é hospedado em uma conta de organização no github, então para usar tem que pagar.

![image](https://user-images.githubusercontent.com/807599/233415607-0401bde4-3b43-4823-b4bf-7a157db5d566.png)

**Comment by Azanniel** [comment]
Infelizmente @luzfcb hehe
E já existe alguma opção de deploy usada por você hoje para recomendar?

Caso não, podemos ver a viabilidade de usar o próprio Github pages

**Comment by luzfcb** [comment]
A @tiidadavena comentou comigo que a [Python Nordeste 2023](https://github.com/pythonNordeste/pyne2023) tá usando https://netlify.com/

Github pages pela minha experiencia tambem funciona super bem tambem.

**Comment by Azanniel** [comment]
Conseguimos usar o netlify? Qual seriam os impedimentos?

**Comment by rougeth** [comment]
Olá pessoal, Gabriel me pingou perguntando dos sites da Python Brasil. Todos os sites da pybr são hospedados no Github Pages. O processo funciona mais ou menos assim: o código fonte fica na branch `main` e uma Github Action fica responsável por fazer o deploy:

1. A Action instala Node, NPM e as dependências no packages.json
2. Roda os testes (se tiverem algum)
3. Roda o build do site
4. Copia todos os arquivos do site gerado e cria um commit no mesmo repositório do site na branch `gh-pages` (pode customizar). É aqui que a mágica acontece, na configuração do repositório você define qual branch contém o código gerado do site.

E pronto, Github identifica que tem conteúdo novo na branch e faz o deploy.

Um exemplo do arquivo fonte da action: https://github.com/pythonbrasil/pybr2022-site/blob/main/.github/workflows/manual.yml

O processo é simples, vocês podem usar qualquer framework (ex: next.js) e o site não precisa ficar na conta de ninguém.

> Conseguimos usar o netlify? Qual seriam os impedimentos?

Precisa adicionar cartão de crédito na conta do Netlify e eles cobram automaticamente e sem comunicar quando passa dos limites do plano free. Não recomendo.

**Comment by Azanniel** [comment]
Perfeito @rougeth 

Iremos mudar nossa estratégia para o github pages, logo estaremos criando o workflow para realização do deploy.

**Comment by Azanniel** [comment]
Com essa decisão foi criada a issue https://github.com/PyNorte/pynorte2023-site/issues/7 que terá por objetivo implementar esse workflow.
